// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMCNBIpYGyz2DLZsFJ2Ivf3Llv_Q6wyOU',
    appId: '1:983701965581:web:2a0828710f24a0fe563e44',
    messagingSenderId: '983701965581',
    projectId: 'ecommerce-ae40d',
    authDomain: 'ecommerce-ae40d.firebaseapp.com',
    storageBucket: 'ecommerce-ae40d.firebasestorage.app',
    measurementId: 'G-9RF2THGR1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyt2Xqq6SdqqnC7qCRzXQVeFN1dt3ojjI',
    appId: '1:983701965581:android:6b82458d26ba6a16563e44',
    messagingSenderId: '983701965581',
    projectId: 'ecommerce-ae40d',
    storageBucket: 'ecommerce-ae40d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5vOu5pJSIgQALfJ76E-JRiaGiBUKNn4w',
    appId: '1:983701965581:ios:8740e731f8089c93563e44',
    messagingSenderId: '983701965581',
    projectId: 'ecommerce-ae40d',
    storageBucket: 'ecommerce-ae40d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5vOu5pJSIgQALfJ76E-JRiaGiBUKNn4w',
    appId: '1:983701965581:ios:8740e731f8089c93563e44',
    messagingSenderId: '983701965581',
    projectId: 'ecommerce-ae40d',
    storageBucket: 'ecommerce-ae40d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMCNBIpYGyz2DLZsFJ2Ivf3Llv_Q6wyOU',
    appId: '1:983701965581:web:604330e88735f9a7563e44',
    messagingSenderId: '983701965581',
    projectId: 'ecommerce-ae40d',
    authDomain: 'ecommerce-ae40d.firebaseapp.com',
    storageBucket: 'ecommerce-ae40d.firebasestorage.app',
    measurementId: 'G-GM8BSRR2Y0',
  );
}
